spring.application.name=bakery-shop

spring.datasource.url=jdbc:postgresql://localhost:5432/bakery_shop
spring.datasource.username=postgres
spring.datasource.password=change-me
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=admin
spring.security.user.password=change-me

# spring.flyway.enabled=true
# spring.flyway.locations=classpath:db/migration
